version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/scr/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    command: yarn dev